// Generated by CoffeeScript 1.10.0
(function() {
  var UnreachableCodeAfterReturn, getIndentLength;

  getIndentLength = function(str) {
    var out;
    out = -1;
    str.replace(/^(\s*)[^#\s]/, function(spaces) {
      out = spaces.length;
    });
    return out;
  };

  module.exports = UnreachableCodeAfterReturn = (function() {
    function UnreachableCodeAfterReturn() {}

    UnreachableCodeAfterReturn.prototype.rule = {
      name: 'unreachable_code_after_return',
      level: 'error',
      message: 'Unreachable code after return',
      description: ''
    };

    UnreachableCodeAfterReturn.prototype.curr_return_indent = Infinity;

    UnreachableCodeAfterReturn.prototype.lintLine = function(line, lineApi) {
      var curr_line_indent;
      if (lineApi.lineNumber === 0) {
        return null;
      }
      curr_line_indent = getIndentLength(line);
      if (curr_line_indent !== -1 && curr_line_indent < this.curr_return_indent) {
        this.curr_return_indent = Infinity;
      }
      if (curr_line_indent >= this.curr_return_indent) {
        return true;
      }
      if (/^\s*return/.test(line)) {
        this.curr_return_indent = curr_line_indent;
      }
      return false;
    };

    return UnreachableCodeAfterReturn;

  })();

}).call(this);
